
  CREATE TABLE "BPM_TASK_CARDS" 
   (	"CARD_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TASK_NUMBER" NUMBER NOT NULL ENABLE, 
	"CARD_TEXT" VARCHAR2(4000) NOT NULL ENABLE, 
	"STATUS_CODE" VARCHAR2(30) DEFAULT 'NEW' NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER DEFAULT ON NULL 10 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(200) NOT NULL ENABLE, 
	"CREATED_TS" TIMESTAMP (6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(200), 
	"UPDATED_TS" TIMESTAMP (6), 
	 CONSTRAINT "BPM_TASK_CARDS_PK" PRIMARY KEY ("CARD_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BPM_TASK_CARDS" ADD CONSTRAINT "BPM_TASK_CARDS_FK1" FOREIGN KEY ("TASK_NUMBER")
	  REFERENCES "BPM_WORKFLOW_TASKS" ("TASK_NUMBER") ENABLE;
  ALTER TABLE "BPM_TASK_CARDS" ADD CONSTRAINT "BPM_TASK_CARDS_FK2" FOREIGN KEY ("STATUS_CODE")
	  REFERENCES "BPM_TASK_STATUSES" ("STATUS_CODE") ENABLE;

  CREATE INDEX "BPM_TASK_CARDS_IX1" ON "BPM_TASK_CARDS" ("TASK_NUMBER", "STATUS_CODE", "DISPLAY_ORDER") 
  ;