
  CREATE TABLE "BPM_TASK_STATUSES" 
   (	"STATUS_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"STATUS_LABEL" VARCHAR2(100) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE, 
	"CARD_CSS_CLASS" VARCHAR2(50), 
	 CONSTRAINT "BPM_TASK_STATUSES_PK" PRIMARY KEY ("STATUS_CODE")
  USING INDEX  ENABLE
   ) ;