
  CREATE TABLE "BPM_WORKFLOW_TASKS" 
   (	"TASK_NUMBER" NUMBER NOT NULL ENABLE, 
	"TASK_ID" VARCHAR2(64), 
	"TITLE" VARCHAR2(500), 
	"TASK_DEF_NAME" VARCHAR2(200), 
	"CATEGORY" VARCHAR2(200), 
	"STATE" VARCHAR2(50), 
	"PRIORITY" NUMBER, 
	"ASSIGNEE_ID" VARCHAR2(200), 
	"ASSIGNEE_TYPE" VARCHAR2(50), 
	"CREATED_BY" VARCHAR2(200), 
	"CREATED_TS" TIMESTAMP (6), 
	"ASSIGNED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6), 
	"FROM_USER_NAME" VARCHAR2(200), 
	"FROM_USER_DISPLAY" VARCHAR2(200), 
	"OWNER_USER" VARCHAR2(200), 
	"IDENTIFICATION_KEY" VARCHAR2(200), 
	"APPROVAL_DURATION" NUMBER,
	"REFRESHED_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"LAST_ACTION" VARCHAR2(50), 
	"LAST_ACTION_TS" TIMESTAMP (6), 
	"LAST_ACTION_STATUS" VARCHAR2(50), 
	"LAST_ACTION_RESPONSE" VARCHAR2(4000), 
	"TRACKING_STATUS" VARCHAR2(30) DEFAULT 'NEW' NOT NULL ENABLE, 
	 CONSTRAINT "BPM_WORKFLOW_TASKS_PK" PRIMARY KEY ("TASK_NUMBER")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "BPM_WORKFLOW_TASKS" ADD CONSTRAINT "BPM_WORKFLOW_TASKS_FK_STATUS" FOREIGN KEY ("TRACKING_STATUS")
	  REFERENCES "BPM_TASK_STATUSES" ("STATUS_CODE") ENABLE;